### ISSUE TITLE
MEDUSA NODES generated hair cannot be converted to particle hair

### ISSUE THREAD

**Issue by SnakeHX** [ikakupa/medusa-nodes-bug-reports#3]
The hair generated by MEDUSA NODES cannot be converted into Particle hair, but the original Particle hair of blender can be converted, not sure if it is a bug? Sorry for my bad English.

https://user-images.githubusercontent.com/124753073/217418741-235ff4ca-8c07-4bcf-bb35-e6f94683dcdf.mp4

**Comment by ikakupa** [comment]
Hello @SnakeHX, 
Medusa Nodes modifier on the  Hair object should be applied first. After that you can enter the sculpt mode and convert the hairs to particle hairs.

Let me know if that helps.

**Comment by SnakeHX** [comment]
YES, it would be better if there is a conversion button on the plugin panel.

**Comment by SnakeHX** [comment]
By the way look forward to more video tutorials on modifiers.

**Comment by ikakupa** [comment]
Yes, it would be better to have such functionality, as an operator directly in the Medusa Nodes panel.

I got little busy with bugs and addon functionality improvements, that's why there where no new tutorials.
