### ISSUE TITLE
Whether the guide line can be individually adjusted to control points?

### ISSUE THREAD

**Issue by SnakeHX** [ikakupa/medusa-nodes-bug-reports#4]
I want to make the control .points of the guide line less, but the adjustment has no effect

**Comment by ikakupa** [comment]
Hey SnakeHX,

Do you mean you would like to change the Control Point Count of the Guide Curves independently from the Hair object?
Sorry, what exactly do you mean by that?

**Comment by SnakeHX** [comment]
Sorry, I didn't express myself very clearly. What I mean is that currently the control points of the green guide line are as many as the control points of the hair. I want to set the control points of the guide line to 6, but the control points of the hair remain the same, and now the control points of the guide line are associated with the hair drive Yes, it cannot be set separately. For example, the guide line of Maya's xgen can be set but the number of control points can be set.
![image](https://user-images.githubusercontent.com/124753073/217982863-4d3442c3-e5d2-4e5a-b4aa-b7b1396a1877.png)

**Comment by ikakupa** [comment]
Yes, this should be done indeed. I am  going to look into that. I will try to make them separately editable for the the next update.
