### ISSUE TITLE
Region Maps - Possible Problem

### ISSUE THREAD

**Issue by andersonbcarlos** [ikakupa/medusa-nodes-bug-reports#9]
As you can see in the image, there are two guides, but apparently the Region Map is not working
![Captura de tela 2023-03-09 122043](https://user-images.githubusercontent.com/36510908/224070170-2a0db0e7-5693-4b18-8b89-dd0d3798d270.png)

**Comment by ikakupa** [comment]
Hello @andersonbcarlos,

I was going to point out the fact that the the region map in the screenshot has a falloff painted on it, which most likely is causing the issue, probably I should have made it more clear in tutorial.
I assume you got around this problem already.

Cheers!

**Comment by andersonbcarlos** [comment]
That was it!
Thanks!
